name: Docker ドキュメント
lang: ja_JP
url:      "http://lfstranslation"
baseurl:  "/docker"
keep_files: ["v17.06", "v18.03", "v18.09", ".git"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      toc_min: 2
      toc_max: 3
      tree: true
  # Hide Enterprise content from sitemap, and include banner in stubs that
  # content has moved to mirantis
  - scope:
      path: "datacenter"
    values:
      enterprise: true
      hide_from_sitemap: true
      title: Docker Enterprise は Mirantis に移転しました。
  - scope:
      path: "ee"
    values:
      enterprise: true
      hide_from_sitemap: true
      title: Docker Enterprise は Mirantis に移転しました。
