command: docker config rm
aliases: remove
short: 1 つまたは複数の Config を削除します。
long: 1 つまたは複数の Config を削除します。
usage: docker config rm CONFIG [CONFIG...]
pname: docker config
plink: docker_config.yaml
deprecated: false
min_api_version: "1.30"
experimental: false
experimentalcli: false
kubernetes: false
swarm: true

