command: docker config create
short: ファイルまたは標準入力から config を生成します。
long: ファイルまたは標準入力から config を生成します。
usage: docker config create [オプション] CONFIG file|-
pname: docker config
plink: docker_config.yaml
options:
- option: label
  shorthand: l
  value_type: list
  description: Config ラベル。
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: template-driver
  value_type: string
  description: テンプレートドライバー。
  deprecated: false
  min_api_version: "1.37"
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
deprecated: false
min_api_version: "1.30"
experimental: false
experimentalcli: false
kubernetes: false
swarm: true

