command: docker config inspect
short: 1 つまたは複数の Config についての詳細情報を表示します。
long: 1 つまたは複数の Config についての詳細情報を表示します。
usage: docker config inspect [オプション] CONFIG [CONFIG...]
pname: docker config
plink: docker_config.yaml
options:
- option: format
  shorthand: f
  value_type: string
  description: Go 言語テンプレートを使って出力をフォーマットします。
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: pretty
  value_type: bool
  default_value: "false"
  description: 読みやすい書式で内容を出力します。
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
deprecated: false
min_api_version: "1.30"
experimental: false
experimentalcli: false
kubernetes: false
swarm: true

